apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-coredns
  namespace: kube-system
data:
  Corefile: |-
    .:53 {
        cache 30
        errors stderr
        etcd ericsson.com. {
          path /skydns
          endpoint http://etcd-cluster.kube-system:2379
        }
        health
        loadbalance round_robin
        prometheus localhost:9153
        proxy . /etc/resolv.conf
    }

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: coredns-coredns
  name: coredns-coredns
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coredns-coredns
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: coredns-coredns
    spec:
      containers:
      - args:
        - -conf
        - /etc/coredns/Corefile
        image: coredns/coredns:006
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: coredns
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/coredns
          name: config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: Corefile
            path: Corefile
          name: coredns-coredns
        name: config-volume

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
  labels:
    app: coredns-coredns
  name: coredns-coredns
  namespace: kube-system
spec:
  ports:
  - name: dns
    nodePort: 32373
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    nodePort: 32373
    port: 53
    protocol: TCP
    targetPort: 53
  selector:
    app: coredns-coredns
  sessionAffinity: None
  type: NodePort
